name: Minecart
version: 2.4.0
description: plugin responsible for managing the payment orders made by the Minecart
author: SnowRunescape
website: https://minecart.com.br

main: br.com.minecart.Minecart
softdepend: [PlaceholderAPI]

commands:
    minecart:
        description: list version and commands
        aliases: []
    mykeys:
        description: list with all the keys the player has to activate
        aliases: [minhaskeys]
    redeemcash:
        description: redeem cash purchased
        aliases: [resgatarcash]
    redeemkey:
        description: redeem key purchased
        aliases: [redeemvip, resgatarvip, resgatarkey]